### ISSUE TITLE
Error building with examples on Ubuntu 20.04.

### ISSUE THREAD

**Issue by tarekmuallim** [luxonis/depthai-core#506] opened 2022-06-20 12:49 UTC
Hi,

I am have problems building depthai-core with examples on Ubuntu 20.04.

I applied:

```
cmake -S. -Bbuild -D'CMAKE_BUILD_TYPE=RELEASE' -D'BUILD_SHARED_LIBS=ON' -D'CMAKE_INSTALL_PREFIX=/usr/local' -D'DEPTHAI_BUILD_EXAMPLES=ON'
cmake --build build 
```

And I get this error:
```
Scanning dependencies of target camera_mobilenet_sync
[ 56%] Building CXX object examples/CMakeFiles/camera_mobilenet_sync.dir/MobileNet/camera_mobilenet_sync_example.cpp.o
[ 56%] Linking CXX executable camera_mobilenet_sync
/usr/bin/ld: CMakeFiles/camera_mobilenet_sync.dir/MobileNet/camera_mobilenet_sync_example.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/camera_mobilenet_sync.dir/build.make:154: examples/camera_mobilenet_sync] Error 1
make[1]: *** [CMakeFiles/Makefile2:2412: examples/CMakeFiles/camera_mobilenet_sync.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Any idea what is the problem?

**Comment by themarpe** [comment] 2022-06-20 12:55
Hi @tarekmuallim 

Thanks for reporting - I was actually able to reproduce this error myself just a day ago. Should be fixed in this PR: https://github.com/luxonis/depthai-core/pull/500

Can you give it a try and let me know if it works for you as intended? 

Will be merged into develop soon & a new release made in cca 2w hopefully

**Closed** 2022-06-20 14:13 UTC
